### PR TITLE
Binary search support

### PR DESCRIPTION
**Pull request by mintern**
#8 with some tweaks:

- Bumps version to 1.3 instead of 1.2.4
- Adds copyright/licensing boilerplate
- Updates changelog and readme
- Aligns code more closely with OpenJDK 8

### CODE REVIEW

**Comment by mintern** [comment]
@sabi0 Since this is an obvious copy-paste-edit of the JDK 8 sources—and you said so yourself—I'm going to go ahead and release this under the JDK's GPLv2+CE license. Please let me know if that will be a problem.

Thanks again for the contribution!

**Comment by mintern** [comment]
...and I just deployed it, so it should be available soon in the Maven Central Repository as version 1.3.

**Comment by sabi0** [comment]
Hi Brandon,

GPLv2+CE is ok with me.

One thing I didn't mention though is that I borrowed the code from Oracle's
JDK not OpenJDK, if that matters.

--
With kind regards,
Dmitry

**Comment by mintern** [comment]
I think it's all the same :smile:

**Pull request merged**
